#!/usr/bin/env bash
#this script is for reason to configure web-02 to be identical to web-01 using automation

sudo apt update
sudo apt install -y nginx

hostname=$(hostname)

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        add_header X-Served-By "$hostname";
	}
}
" | sudo tee /etc/nginx/sites-available/default

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

sudo nginx -t
sudo service nginx restart
