#!/usr/bin/env bash
#this script is for  pings an IP address passed as an argument.

#if [ $# -eq 0 ]
#	then
#		echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
#fi
#ping -c 5 "$1"

if [ "$#" -ne 1 ]
then
	echo "Usage: $0 {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
