#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes
# display hours from 0 to 12
# display minutes from 1 to 59

hour=0
while [ $hour -le 12 ]
        do
                echo "Hour: $hour"
		mn=1
		while [ $mn -le 59 ]
			do
				echo "$mn"
				((mn++))
			done
		((hour++))
        done
