#!/usr/bin/env bash
# This script is displaying The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

list=$(ls)
for items in $list
	do
		echo "$items" | cut -d '-' -f2
	done
