#!/usr/bin/env bash
# This script is giving information about the school file
# if the file exists: school file exists
# if the file does not exist: school file does not exist
# if the file exists and is empty: school file is empty
# if the file exists and is not empty: school file is not empty
# if the file exists and is a regular file: school is a regular file
# if the file exists and is not a regular file: (nothing)

fl="school"

if [ -e "$fl" ]
	then
    		echo "school file exists"
    if [ -s "$fl" ]
	then
        	echo "school file is not empty"
    else
       		echo "school file is empty"
    fi

    if [ -f "$fl" ]
	then
        	echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
