#!/usr/bin/env bash
#this script configures the container to fit these requirements
#nginx must be running as nginx user
#nginx must be listening on all active IPs on port 8080

pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
